#!/usr/bin/env python3
"""Lint-debt baseline gate.

This repository carries a large amount of inherited Ruff debt. Fixing it all at
once would mean a mechanical rewrite of most of the tree, so instead the debt is
frozen in a committed baseline and CI enforces that it never grows.

The rule enforced by ``check``:

* every (file, rule) pair may have at most as many findings as the baseline
  records for it -- so a change cannot add a new violation, not even to a file
  that is already dirty;
* the global total may not increase.

Decreases are always allowed and are reported. Run ``update`` to record them,
which is the only supported way to shrink the baseline.

Commands
--------
check   Compare the working tree against the baseline. Exit 1 if debt grew.
update  Rewrite the baseline from the working tree. Refuses to record an
        increase unless --allow-increase is passed.
report  Print the full outstanding debt, by rule and by directory. This is the
        view that keeps the inherited findings from disappearing.

The baseline is keyed by repository-relative path so it is stable regardless of
where the command runs from.
"""

from __future__ import annotations

import argparse
import collections
import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_BASELINE = REPO_ROOT / ".lint-baseline.json"


def ruff_version() -> str:
    proc = subprocess.run(
        [sys.executable, "-m", "ruff", "--version"],
        capture_output=True,
        text=True,
        check=True,
    )
    return proc.stdout.strip()


def collect(paths: list[str], root: Path) -> dict[str, dict[str, int]]:
    """Findings per file per rule, keyed by path relative to `root`."""
    proc = subprocess.run(
        [sys.executable, "-m", "ruff", "check", "--output-format=json", *paths],
        cwd=root,
        capture_output=True,
        text=True,
    )
    # 0 = clean, 1 = findings. Anything else is ruff failing to run.
    if proc.returncode not in (0, 1):
        sys.stderr.write(proc.stderr)
        raise SystemExit(f"ruff exited {proc.returncode}")

    counts: dict[str, dict[str, int]] = collections.defaultdict(
        lambda: collections.defaultdict(int)
    )
    for finding in json.loads(proc.stdout or "[]"):
        rel = Path(finding["filename"]).resolve().relative_to(root.resolve())
        counts[rel.as_posix()][finding["code"]] += 1
    return {f: dict(sorted(r.items())) for f, r in sorted(counts.items())}


def total_of(counts: dict[str, dict[str, int]]) -> int:
    return sum(sum(rules.values()) for rules in counts.values())


def load_baseline(path: Path) -> dict:
    if not path.exists():
        raise SystemExit(
            f"no baseline at {path}. Create one with:\n"
            f"  python scripts/lint_baseline.py update"
        )
    return json.loads(path.read_text())


def write_baseline(path: Path, counts: dict[str, dict[str, int]]) -> None:
    payload = {
        "_comment": (
            "Frozen Ruff debt. Generated by scripts/lint_baseline.py; do not "
            "hand-edit. A change may never raise any count here. Run "
            "`make lint-baseline-update` after genuinely reducing debt."
        ),
        "ruff_version": ruff_version(),
        "total": total_of(counts),
        "files": counts,
    }
    path.write_text(json.dumps(payload, indent=2, sort_keys=False) + "\n")


def cmd_check(args) -> int:
    baseline = load_baseline(args.baseline)
    recorded = baseline.get("files", {})
    current = collect(args.paths, args.root)

    if baseline.get("ruff_version") and baseline["ruff_version"] != ruff_version():
        print(
            f"warning: baseline was generated with {baseline['ruff_version']!r} "
            f"but {ruff_version()!r} is installed. Rule changes between versions "
            f"can shift counts; regenerate the baseline if this is deliberate.",
            file=sys.stderr,
        )

    regressions = []
    for path, rules in sorted(current.items()):
        allowed = recorded.get(path, {})
        for rule, count in sorted(rules.items()):
            budget = allowed.get(rule, 0)
            if count > budget:
                regressions.append((path, rule, budget, count))

    current_total, baseline_total = total_of(current), baseline.get("total", 0)

    if regressions:
        print("Lint debt increased. New findings are not allowed:\n")
        for path, rule, budget, count in regressions:
            print(f"  {path}:{rule}  baseline {budget} -> now {count}")
        print(
            f"\n{len(regressions)} rule/file pair(s) regressed. "
            f"Total {baseline_total} -> {current_total}."
            f"\nFix the new findings. Do not raise the baseline to accommodate them."
        )
        return 1

    if current_total > baseline_total:
        print(
            f"Global lint debt rose from {baseline_total} to {current_total} "
            f"without a per-file regression; the baseline may be stale."
        )
        return 1

    if current_total < baseline_total:
        print(
            f"Lint debt is DOWN: {baseline_total} -> {current_total} "
            f"({baseline_total - current_total} fewer). "
            f"Run `make lint-baseline-update` to lock the improvement in."
        )
    else:
        print(f"Lint debt unchanged at {current_total}. No new findings.")
    return 0


def cmd_update(args) -> int:
    current = collect(args.paths, args.root)
    new_total = total_of(current)
    if args.baseline.exists():
        old_total = load_baseline(args.baseline).get("total", 0)
        if new_total > old_total and not args.allow_increase:
            print(
                f"Refusing to raise the baseline from {old_total} to {new_total}.\n"
                f"The baseline exists to stop debt growing. Fix the new findings, "
                f"or pass --allow-increase if this is a deliberate, explained "
                f"change such as a Ruff upgrade or a newly enabled rule."
            )
            return 1
        print(f"Baseline {old_total} -> {new_total}")
    write_baseline(args.baseline, current)
    print(f"Wrote {args.baseline}")
    return 0


def cmd_report(args) -> int:
    current = collect(args.paths, args.root)
    by_rule: collections.Counter = collections.Counter()
    by_dir: collections.Counter = collections.Counter()
    for path, rules in current.items():
        top = path.split("/")[0]
        for rule, count in rules.items():
            by_rule[rule] += count
            by_dir[top] += count

    total = total_of(current)
    print(f"Outstanding Ruff debt: {total} findings across {len(current)} files\n")
    print("By rule:")
    for rule, count in by_rule.most_common(args.limit):
        print(f"  {count:6d}  {rule}")
    print("\nBy top-level path:")
    for top, count in by_dir.most_common():
        print(f"  {count:6d}  {top}")
    print("\nWorst files:")
    worst = sorted(current.items(), key=lambda kv: -sum(kv[1].values()))
    for path, rules in worst[: args.limit]:
        print(f"  {sum(rules.values()):6d}  {path}")
    print("\nEvery individual finding: uv run ruff check .")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--baseline", type=Path, default=DEFAULT_BASELINE)
    parser.add_argument("--root", type=Path, default=REPO_ROOT)
    parser.add_argument("--paths", nargs="*", default=["."])
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("check").set_defaults(func=cmd_check)
    upd = sub.add_parser("update")
    upd.add_argument("--allow-increase", action="store_true")
    upd.set_defaults(func=cmd_update)
    rep = sub.add_parser("report")
    rep.add_argument("--limit", type=int, default=15)
    rep.set_defaults(func=cmd_report)
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
